### ISSUE TITLE
video watermarking

### ISSUE THREAD

**Issue by GitHubber15614** [sourab-sharma/TouchToRecord#10]
I'd like to know how to add watermark to a video based on this project,please help on this

**Comment by zzhopen** [comment]
I'd like to know how to add watermark to a video based on this project, too

**Comment by sourab-sharma** [comment]
For some reasons, I can't work to give you working solution at the moment.
You will have to try yourself.
Go to Processor.java class , make some function like you see for combineVideoAndAudio

Use ffmpeg command like :

          this.mCommand.add("-vf");
	  this.mCommand.add("movie=" + overlayImage +" [logo];[in][logo] overlay=0:0 [out]");

overlayImage  is the path of image, and follow some documentation for other params from here 
https://ffmpeg.org/ffmpeg-filters.html

and when it works, please do post working solution anywhere online you like and drop a link here,
so that I can close this issue.

**Comment by GitHubber15614** [comment]
Thanks,I will have a try!
